name: Update Site and Deploy to IONOS

on:
  schedule:
    - cron: '*/30 * * * *'  # Runs every 30 minutes
  workflow_dispatch:  # Allows for manual deployment

jobs:
  update_site:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install WinHTTrack
        run: sudo apt-get install -y httrack

      - name: Download Framer Site
        run: |
          # Remove 'site' directory if it exists and create a new one
          rm -rf ./site
          mkdir site
          httrack "${{ secrets.FRAMER_SITE_URL }}" -O "./site" --disable-security-limits -%v
        env:
          FRAMER_SITE_URL: ${{ secrets.FRAMER_SITE_URL }}

      - name: Remove Framer Watermark
        run: |
          # Remove the Framer badge container HTML
          find ./site -type f -name "*.html" -exec sed -i '/<div id="__framer-badge-container"><\/div>/d' {} \;
          # Remove the Framer badge CSS
          find ./site -type f -name "*.css" -exec sed -i '/#__framer-badge-container {/,/z-index: 314159/d' {} \;

      - name: Commit and Push Changes
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --local user.email "your-email@example.com"
          git config --local user.name "Your Name"
          git add .
          git commit -m "Automated update of site content" || echo "No changes to commit"
          git push https://$GH_PAT@github.com/bmc-admin/brightmoveconsultants.git HEAD:main

  deploy:
    runs-on: ubuntu-latest
    needs: update_site  # Ensure deployment only happens after site update

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.IONOS_SSH_KEY }}

      - name: Check Directory Permissions
        run: |
          ssh -o StrictHostKeyChecking=no -p ${{ secrets.IONOS_PORT }} ${{ secrets.IONOS_USERNAME }}@${{ secrets.IONOS_HOST }} "ls -ld ~/brightmoveconsultants"

      - name: Clean Webspace Directory
        run: |
          ssh -o StrictHostKeyChecking=no -p ${{ secrets.IONOS_PORT }} ${{ secrets.IONOS_USERNAME }}@${{ secrets.IONOS_HOST }} "rm -rf ~/brightmoveconsultants/*"

      - name: Upload Files to IONOS
        run: |
          rsync -avz -e "ssh -p ${{ secrets.IONOS_PORT }}" --delete --exclude '.git/' ./site/splendid-successes-043935.framer.app/ ${{ secrets.IONOS_USERNAME }}@${{ secrets.IONOS_HOST }}:~/brightmoveconsultants/
